# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H13_HYNpkM0Va_Uhzf7Ee4uSP-ANiJwz
"""
#3-1 practice
def right_justify(s):
	i = len(s)
	while i < 70:
		print(" ", end = "")
		i += 1
	print(s)

right_justify("Sunghas")

#3-2 practice 
def do_twice(func, arg):
  func(arg)
  func(arg)


def print_twice(arg):
  print(arg)
  print(arg)

def do_four(func, arg):
  do_twice(func, arg)
  do_twice(func, arg)
  
do_twice(print_twice, "spam")
print()
do_four(print_twice, "spam")

#3-3 practice

def do_twice(func):
  func()
  func()
  
def print_cross():
  print("+----", end = "")

def print_il():
  print("|    ", end = "")
  
def print_finish_1():
  do_twice(print_cross)
  print("+")

def print_finish_2():
  do_twice(print_il)
  print("|")
  
def do_four(f):
  do_twice(f)
  do_twice(f)
  
def making_frame():
  print_finish_1()
  do_four(print_finish_2)
  
def making_finish():
  do_twice(making_frame)
  print_finish_1()
  
making_finish()

